### ISSUE TITLE
Is possible run a sequence of compensation?

### ISSUE THREAD

**Issue by cuonglu** [eventuate-tram/eventuate-tram-sagas#9]
Now, I config a saga dsl as below:
 ```
        step()
            .invokeParticipant(this::step1)
            .withCompensation(this::compensation1)
        .step()
            .invokeParticipant(this::step2)
            .withCompensation(this::compensation2)
        .step()
            .invokeParticipant(this::step3)
        .build();
```
When the step 3 fail, I want the compensation1 and compensation2 are run. But now it seen maybe only compensation2 is run as default.

Anyone have a solution?

**Comment by cer** [comment]
I'd expect this to work. For example, https://github.com/microservices-patterns/ftgo-application/blob/master/ftgo-order-service/src/test/java/net/chrisrichardson/ftgo/orderservice/sagas/createorder/CreateOrderSagaTest.java#L105 tests this scenario.

Does `compensation2` send back a success reply? That's required in order for `compensation1` to run.

**Comment by cuonglu** [comment]
@cer 

Oh, I testing again and it's ok.
When I am execute the test, I has not yet define handler for ```compensation2```.

The ```compensation1``` is only send  when receiving the reply from ```compensation2```.
Before that, I think all compensation will be send when it receive the FAIL reply message.

Thanks for you support!!!
