### ISSUE TITLE
ReactiveSaga not started if i use PostgreSQL

### ISSUE THREAD

**Issue by artemio77** [eventuate-tram/eventuate-tram-sagas#97]
Hi @cer. I set up a project with reactive saga with PostgreSQL DB. But when I try to create a new saga instance I got: 

`java.lang.RuntimeException: org.springframework.dao.InvalidDataAccessApiUsageException: No parameter specified for [param5] in query [INSERT INTO eventuate.saga_instance(saga_type, saga_id, state_name, last_request_id, saga_data_type, saga_data_json, end_state, compensating, failed) VALUES(:param1, :param2, :param3, NULL, :param5, :param6, :param7, :param8, :param9)]
	at io.eventuate.common.spring.jdbc.reactive.EventuateSpringReactiveJdbcStatementExecutor.handleDuplicateKeyException(EventuateSpringReactiveJdbcStatementExecutor.java:127) ~[eventuate-common-spring-reactive-jdbc-0.16.0.RELEASE.jar:na
`
I debug your framework and found that you have a custom logic for postgres null parameters but looks like this code have a bug.

My setup:
spring boot version 2.7.9
pg image: eventuateio/eventuate-tram-sagas-mysql:0.20.0.RELEASE
eventuate dependencies:
implementation(platform("io.eventuate.platform:eventuate-platform-dependencies:2022.2.RELEASE"))
implementation("io.eventuate.tram.core:eventuate-tram-spring-reactive-jdbc-kafka")
implementation("io.eventuate.tram.sagas:eventuate-tram-sagas-spring-reactive-orchestration-simple-dsl-starter")

Hint: I tried change DB to MySQL and I don't get this error but in my case I need PostgreSql

**Comment by artemio77** [comment]
@cer @dartartem Any thoughts about this?

**Comment by artemio77** [comment]
@cer Do you have a change to look into this?

**Comment by artemio77** [comment]
@cer Did you had a chance to look into this?

**Comment by cer** [comment]
I fixed a bug in eventuate-common, please test with `eventuatePlatformVersion=2022.3.BUILD-SNAPSHOT`

**Comment by artemio77** [comment]
"@cer, Thank you for your fix. It works fine. Can you explain more about the release cycles? When will it be available in the released version?

**Comment by cer** [comment]
> Thank you for fixing it, @cer. It's working fine. Could you elaborate on the release cycles, please? When is it expected to be available in the upcoming release?"

It's been released 2023.0.RELEASE.
